---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-13-gd3fd8ba
_src_path: .
app_description: a commandline interface for kubernetes cluster
app_name: kubectl
app_repo: https://github.com/kubernetes/kubernetes
app_version_prefix: v
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86_64: amd64
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
download_checksum_cmd: sha256sum
download_checksum_enabled: true
download_checksum_link: https://dl.k8s.io/v{version}/bin/{os}/{arch}/kubectl.sha256
download_link: https://dl.k8s.io/release/v{version}/bin/{os}/{arch}/kubectl
download_type: single-file
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-kubectl
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-kubectl
test_cmd_args: ''
